services:
  s5_auth_api_base:
    build:
      context: ../../../
      dockerfile: devops/docker/s5_auth_api/Dockerfile
    container_name: yp_s5_auth_api
    user: "doorman"
    env_file:
      - ../../.s5_auth_pg.env
      - ../../.s5_auth_redis.env
      - ../../.s5_auth_api.env

  s5_auth_api_dev:
    extends:
      file: service.yml
      service: s5_auth_api_base
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
      target: develop
    command: ["flask", "run", "--host=0.0.0.0"]
    # command: ["tail", "-f", "/dev/null"]
    ports:
      - "5000:5000"
    volumes:
      - ../../../services/s5_auth_api:/usr/src/auth_app
    env_file:
      - ../../.dev.env
    
  s5_auth_api_test:
    extends:
      file: service.yml
      service: s5_auth_api_base
    build:
      target: test
    command: ["flask", "run", "--host=0.0.0.0"]
    env_file:
      - ../../.test.env
    
  s5_auth_api_prod:
    extends:
      file: service.yml
      service: s5_auth_api_base
    build:
      target: production
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--reload", "wsgi_app:app"]
    restart: always
    env_file:
      - ../../.prod.env