version: "3.9"

x-networks:
  &default-networks
  networks:
  - yp_network

networks:
  yp_network:
    driver: bridge

services:
  s1_admin:
    extends:
      file: s1_admin/service.yml
      service: s1_admin_dev
    depends_on:
      - s1_admin_pg
    << : *default-networks

  s1_admin_pg:
    extends:
      file: s1_admin_pg/service.yml
      service: s1_admin_pg
    << : *default-networks

  s2_nginx:
    extends:
      file: s2_nginx/service.yml
      service: s2_nginx_dev
    depends_on:
      - s1_admin
    << : *default-networks

  s3_etl:
    extends:
      file: s3_etl/service.yml
      service: s3_etl_dev
    depends_on:
      - s1_admin_pg
      - s4_movie_es
    << : *default-networks

  s4_movie_api:
    extends:
      file: s4_movie_api/service.yml
      service: s4_movie_api_dev
    depends_on:
      - s4_movie_es
      - s4_movie_redis
    << : *default-networks

  s4_movie_es:
    extends:
      file: s4_movie_es/service.yml
      service: s4_movie_es
    << : *default-networks
    
  s4_movie_redis:
    extends:
      file: s4_movie_redis/service.yml
      service: s4_movie_redis
    << : *default-networks

  s5_auth_api:
    extends:
      file: s5_auth_api/service.yml
      service: s5_auth_api_dev
    depends_on:
      - s5_auth_pg
    << : *default-networks

  s5_auth_pg:
    extends:
      file: s5_auth_pg/service.yml
      service: s5_auth_pg
    << : *default-networks

  s5_auth_redis:
    extends:
      file: s5_auth_redis/service.yml
      service: s5_auth_redis
    << : *default-networks