version: "3.9"

networks:
  yp_network:
    driver: bridge

services:
  s5_auth_api:
    extends:
      file: s5_auth_api/service.yml
      service: s5_auth_api
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
      target: develop
    command: ["flask", "run", "--host=0.0.0.0"]
    # command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../../services/s5_auth_api:/usr/src/auth_app
    env_file:
      - ../.dev.env
    depends_on:
      - s5_auth_pg
    networks:
      - yp_network

  s5_auth_pg:
    extends:
      file: s5_auth_pg/service.yml
      service: s5_auth_pg
    networks:
      - yp_network

  s5_auth_redis:
    extends:
      file: s5_auth_redis/service.yml
      service: s5_auth_redis
    networks:
      - yp_network