version: "3.9"

networks:
  yp_network:
    driver: bridge

services:
  s1_admin:
    extends:
      file: s1_admin/docker-compose.yml
      service: s1_admin
    env_file:
      - ../../.dev.env
    depends_on:
      - s1_admin_pg
    networks:
      - yp_network

  s1_admin_pg:
    extends:
      file: s1_admin_pg/docker-compose.yml
      service: s1_admin_pg
    networks:
      - yp_network