version: "3.9"

networks:
  yp_network:
    driver: bridge

services:
  s1_admin:
    extends:
      file: s1_admin/service.yml
      service: s1_admin
    env_file:
      - ../../.dev.env
    depends_on:
      - s1_admin_pg
    networks:
      - yp_network

  s1_admin_pg:
    extends:
      file: s1_admin_pg/service.yml
      service: s1_admin_pg
    networks:
      - yp_network

  s4_movie_es:
    extends:
      file: s4_movie_es/service.yml
      service: s4_movie_es
    networks:
      - yp_network

  s3_etl:
    extends:
      file: s3_etl/service.yml
      service: s3_etl
    env_file:
      - ../../.dev.env
    depends_on:
      - s1_admin_pg
      - s4_movie_es
    networks:
      - yp_network