version: "3.9"

x-networks:
  &default-networks
  networks:
  - yp_network

networks:
  yp_network:
    driver: bridge

services:
  s5_auth_api:
    extends:
      file: s5_auth_api/service.yml
      service: s5_auth_api_dev
    depends_on:
      - s5_auth_pg
    << : *default-networks

  s5_auth_pg:
    extends:
      file: s5_auth_pg/service.yml
      service: s5_auth_pg
    << : *default-networks

  s5_auth_redis:
    extends:
      file: s5_auth_redis/service.yml
      service: s5_auth_redis
    << : *default-networks