version: "3.9"

x-networks:
  &default-networks
  networks:
  - yp_network

networks:
  yp_network:
    driver: bridge

services:
  s1_admin:
    extends:
      file: s1_admin/service.yml
      service: s1_admin_dev
    depends_on:
      - s1_admin_pg
    << : *default-networks

  s1_admin_pg:
    extends:
      file: s1_admin_pg/service.yml
      service: s1_admin_pg_dev
    << : *default-networks

  s2_nginx:
    extends:
      file: s2_nginx/service.yml
      service: s2_nginx_dev
    depends_on:
      - s1_admin
    << : *default-networks