version: "3.9"

networks:
  yp_network:
    driver: bridge

services:
  s1_admin:
    extends:
      file: s1_admin/service.yml
      service: s1_admin
    env_file:
      - ../.dev.env
    depends_on:
      - s1_admin_pg
    networks:
      - yp_network

  s1_admin_pg:
    extends:
      file: s1_admin_pg/service.yml
      service: s1_admin_pg
    networks:
      - yp_network

  s3_etl:
    extends:
      file: s3_etl/service.yml
      service: s3_etl
    env_file:
      - ../.dev.env
    depends_on:
      - s1_admin_pg
      - s4_movie_es
    networks:
      - yp_network

  s4_movie_api:
    extends:
      file: s4_movie_api/service.yml
      service: s4_movie_api
    env_file:
      - ../.dev.env
    depends_on:
      - s4_movie_es
      - s4_movie_redis
    networks:
      - yp_network

  s4_movie_es:
    extends:
      file: s4_movie_es/service.yml
      service: s4_movie_es
    networks:
      - yp_network
    
  s4_movie_redis:
    extends:
      file: s4_movie_redis/service.yml
      service: s4_movie_redis
    networks:
      - yp_network

  s5_auth_api:
    extends:
      file: s5_auth_api/service.yml
      service: s5_auth_api
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
      target: develop
    command: ["flask", "run", "--host=0.0.0.0"]
    # command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../../services/s5_auth_api:/usr/src/auth_app
    env_file:
      - ../.dev.env
    depends_on:
      - s5_auth_pg
    networks:
      - yp_network

  s5_auth_pg:
    extends:
      file: s5_auth_pg/service.yml
      service: s5_auth_pg
    networks:
      - yp_network

  s5_auth_redis:
    extends:
      file: s5_auth_redis/service.yml
      service: s5_auth_redis
    networks:
      - yp_network