version: "3.9"

services:
  s1_admin_base:
    build:
      context: ../../../
      dockerfile: devops/docker/s1_admin/Dockerfile
    container_name: yp_s1_admin
    user: "ticket_man"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ../../.s1_admin_pg.env
      - ../../.s1_admin.env

  s1_admin_dev:
    extends:
      file: service.yml
      service: s1_admin_base
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
    env_file:
      - ../../.dev.env
    # тома инклюдятся через docker-compose -f docker-compose._volumes.yml
    volumes:
      - ../../../services/s1_admin/movies_admin:/usr/src/app
      - yp_s1_admin_static_volume:/usr/src/app/static

  s1_admin_test:
    extends:
      file: service.yml
      service: s1_admin_base
    env_file:
      - ../../.test.env

  s1_admin_prod:
    extends:
      file: service.yml
      service: s1_admin_base
    restart: always
    env_file:
      - ../../.prod.env