services:
  s5_auth_redis_base:
    image: redis:6.2.5-alpine
    container_name: yp_s5_auth_redis
    command: ["redis-server", "--appendonly", "yes"]

  s5_auth_redis_dev:
    extends:
      file: service.yml
      service: s5_auth_redis_base
    volumes:
      - yp_s5_auth_redis_data:/data
    ports:
      - "6379:6379"

  s5_auth_redis_test:
    extends:
      file: service.yml
      service: s5_auth_redis_base

  s5_auth_redis_prod:
    extends:
      file: service.yml
      service: s5_auth_redis_base
    restart: always