version: "3.9"

services:
  s3_etl:
    build:
      context: ../../../
      dockerfile: devops/docker/s3_etl/Dockerfile
      # args:
      #   uid: ${HOST_UID}
      #   gid: ${HOST_GID}
    container_name: yp_s3_etl
    restart: always
    user: "delivery_man"
    command: ["python3", "etl.py"]
    env_file:
      - ../../.s1_admin_pg.env
      - ../../.s4_movie_es.env
      - ../../.s3_etl.env
      - ../../.dev.env